package config

/**
 * Web platform configuration for canvas-based rendering.
 *
 * This centralizes magic strings that must stay synchronized with index.html.
 * All canvas and module configuration references are defined here.
 */
object WebConfig {
    /**
     * HTML Canvas element ID that hosts the Compose rendering surface.
     * Must match the `<canvas id="...">` element in index.html.
     */
    const val CANVAS_ELEMENT_ID = "ComposeTarget"

    /**
     * Module name for webpack output. Used internally by the Kotlin/wasmJs compiler.
     * Must match `outputModuleName` in build.gradle.kts.
     */
    const val MODULE_NAME = "landing"

    /**
     * JavaScript output filename generated by webpack.
     * Must match `outputFileName` in build.gradle.kts.
     */
    const val JS_OUTPUT_FILENAME = "landing.js"
}
